### ISSUE TITLE
Does not make .pak

### ISSUE THREAD

**Issue by Inmortuae** [LennardF1989/BG3-BagsOfSorting#1]
No .pak file is being created

**Comment by G3n-Zer0** [comment]
Well not sure if they're having the same issue that I am, mine also isn't generating a pak file but, this is the exception I get in cmd:
```
reading D:\Game Mods\BG3\Bags of Sorting\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_9a5ac4783eda4d2aa33dcb04ddf75ee4.png (64x64 B8G8R8A8_UNORM 2D) as (64x64,7 BC3_UNORM 2D a:NonPM)
writing D:\Game Mods\BG3\Bags of Sorting\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_9a5ac4783eda4d2aa33dcb04ddf75ee4.dds
Unhandled exception. System.IO.FileNotFoundException:
File name: 'D:\Game Mods\BG3\Bags of Sorting\LSLibNative.dll'
   at LSLib.LS.BinUtils.CompressLZ4(Byte[] uncompressed, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.BinUtils.Compress(Byte[] uncompressed, CompressionMethod method, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.LSFWriter.Write(Resource resource)
   at BG3.BagsOfSorting.Program.ConvertLSXToLSF(String lsxPath, String lsfPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 624
   at BG3.BagsOfSorting.Program.GenerateRootTemplate(Bag bag, String outputPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 453
   at BG3.BagsOfSorting.Program.GenerateBag(BagConfiguration bagConfiguration, Bag bag) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 294
   at BG3.BagsOfSorting.Program.GenerateBags() in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 276
   at BG3.BagsOfSorting.Program.Main(String[] args) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 163
```

**Comment by Ronin-Kai** [comment]
Can Confirm an Identical Error to G3n-Zer0, save for slightly different file path

```
reading C:\Users\TJ\Downloads\BG3 Stuff\BG3-BagsOfSorting-Windows-x64\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_afa059b2639f4162a398e267f055e616.png (380x380 B8G8R8A8_UNORM 2D) as (380x380,9 BC3_UNORM 2D a:NonPM)
writing C:\Users\TJ\Downloads\BG3 Stuff\BG3-BagsOfSorting-Windows-x64\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_afa059b2639f4162a398e267f055e616.dds
Unhandled exception. System.IO.FileNotFoundException:
File name: 'C:\Users\TJ\Downloads\BG3 Stuff\BG3-BagsOfSorting-Windows-x64\LSLibNative.dll'
   at LSLib.LS.BinUtils.CompressLZ4(Byte[] uncompressed, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.BinUtils.Compress(Byte[] uncompressed, CompressionMethod method, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.LSFWriter.Write(Resource resource)
   at BG3.BagsOfSorting.Program.ConvertLSXToLSF(String lsxPath, String lsfPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 624
   at BG3.BagsOfSorting.Program.GenerateRootTemplate(Bag bag, String outputPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 453
   at BG3.BagsOfSorting.Program.GenerateBag(BagConfiguration bagConfiguration, Bag bag) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 294
   at BG3.BagsOfSorting.Program.GenerateBags() in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 276
   at BG3.BagsOfSorting.Program.Main(String[] args) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 163
```

**Comment by LennardF1989** [comment]
@Inmortuae Do you have the last bit of the log to share? Otherwise this can literally mean anything :)

@G3n-Zer0 @Ronin-Kai Are you both are on 1.0.1 AND have all files extracted? Can you confirm there is actually a LSLibNative.dll in the folder where the batch files are? Which OS are you on? Windows 10/11?

**Comment by Inmortuae** [comment]
Where do I find the log? And I will be able to post the log when I get off work this afternoon

**Comment by G3n-Zer0** [comment]
> @Inmortuae Do you have the last bit of the log to share? Otherwise this can literally mean anything :)
> 
> @G3n-Zer0 @Ronin-Kai Are you both are on 1.0.1 AND have all files extracted? Can you confirm there is actually a LSLibNative.dll in the folder where the batch files are? Which OS are you on? Windows 10/11?

Yeah, 1.0.1, although I tested 1.0 as well and got a similar error, and Windows 10 pro.
<a href="https://imgur.com/eYd9YD9"><img src="https://i.imgur.com/eYd9YD9.png" title="source: imgur.com" /></a>

**Comment by zenq-tw** [comment]
Same for me. `.dll` file and both files (`.lsx` and `.lsf`) are present. Tried to fix it in different ways, without success.

Win11 Home.
Full console output:

```
PS C:\Games\BG3\Mods\BagsOfSorting> .\BG3.BagsOfSorting.exe --generate-bags
Microsoft (R) DirectX Texture Converter [DirectXTex] Version 2023.6.14.1
Copyright (C) Microsoft Corp.

reading C:\Games\BG3\Mods\BagsOfSorting\Output\Bags\Public\GustavDev\Assets\Textures\Icons\BOS_11fbe07a1a904808829bbbba19c3d791.png (64x64 B8G8R8A8_UNORM 2D) as (64x64,7 BC3_UNORM 2D a:NonPM)
writing C:\Games\BG3\Mods\BagsOfSorting\Output\Bags\Public\GustavDev\Assets\Textures\Icons\BOS_11fbe07a1a904808829bbbba19c3d791.dds
Microsoft (R) DirectX Texture Converter [DirectXTex] Version 2023.6.14.1
Copyright (C) Microsoft Corp.

reading C:\Games\BG3\Mods\BagsOfSorting\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_11fbe07a1a904808829bbbba19c3d791.png (380x380 B8G8R8A8_UNORM 2D) as (380x380,9 BC3_UNORM 2D a:NonPM)
writing C:\Games\BG3\Mods\BagsOfSorting\Output\Bags\Public\Game\GUI\Assets\Tooltips\ItemIcons\BOS_11fbe07a1a904808829bbbba19c3d791.dds
Unhandled exception. System.IO.FileNotFoundException:
File name: 'C:\Games\BG3\Mods\BagsOfSorting\LSLibNative.dll'
   at LSLib.LS.BinUtils.CompressLZ4(Byte[] uncompressed, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.BinUtils.Compress(Byte[] uncompressed, CompressionMethod method, CompressionLevel compressionLevel, Boolean chunked)
   at LSLib.LS.LSFWriter.Write(Resource resource)
   at BG3.BagsOfSorting.Program.ConvertLSXToLSF(String lsxPath, String lsfPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 624
   at BG3.BagsOfSorting.Program.GenerateRootTemplate(Bag bag, String outputPath) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 453
   at BG3.BagsOfSorting.Program.GenerateBag(BagConfiguration bagConfiguration, Bag bag) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 294
   at BG3.BagsOfSorting.Program.GenerateBags() in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 276
   at BG3.BagsOfSorting.Program.Main(String[] args) in G:\Projects\Lennard\BG3.BagsOfSorting\Src\BG3.BagsOfSorting\Program.cs:line 163
```

Bags.json:
```json
{
  "Bags": [
    {
      "MapKey": "11fbe07a-1a90-4808-829b-bbba19c3d791",
      "DisplayName": "One",
      "Description": "Two",
      "TechnicalDescription": "Three",
      "AutoPickupCondition": null,
      "Color": "Green",
      "ItemIcon": {
        "Name": "Item_BASE_ALCH_Extract_Earth",
        "Custom": false,
        "Generate": true
      },
      "TooltipIcon": {
        "Name": "Item_BASE_ALCH_Extract_Earth",
        "Custom": false,
        "Generate": true
      },
      "Amount": 1
    }
  ],
  "AdditionalTreasures": {},
  "AlignGeneratedItemIconsRight": false
}
```

**Comment by LennardF1989** [comment]
I think I'll have to resort to a different method of getting LSLibNative to work, thanks, I'll investigate this!

**Comment by Inmortuae** [comment]
Alrighty im home im on windows 10 pro on ver 1.0.1

![image](https://github.com/LennardF1989/BG3-BagsOfSorting/assets/60497629/268b4b95-55e9-455e-b813-597140ea76c9)

**Comment by LennardF1989** [comment]
Could all you of you give this version a try? https://github.com/LennardF1989/BG3-BagsOfSorting/releases/tag/v1.0.2

**Comment by Inmortuae** [comment]
Works Perfectly. Thank you my guy

**Comment by Ronin-Kai** [comment]
Didn't have time today to give an update until now, but I tried the posted version and just wanted to say it fixed it for me as well.  Thanks for your work!
